[package]
name = "base64-convert-csv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
rand = "0.8.5"
chrono = "0.4.31"
csv = "1.1.6"
